### ISSUE TITLE
SSRequest.DiagramEndpoint.Name v3.0 has different use in V3.1

### ISSUE THREAD

**Issue by careybeall** [KeyBridge/lib-openssrf#1]
SSRFv3.1 changes:
(1) Replaced SSRequest/DiagramEndpoint/Name with SSRequest/DiagramEndpoint/EndpointID 
(2) Repurposed SSRequest/DiagramEndpoint/Name to be a short text endpoint description
(3) Added a new (S100) long text SSRequest/DiagramEndpoint/Description

The conversion utility  from v3.0 to v3.1 misses this change, probably because Name is still a valid data item (it should be converted to ID). Here are the errors received during conversion:  
SSRequest.diagramEndpoint instance requires (TString) endpointID
SSRequest.diagramLine instance requires (TString) rxEndpointID
SSRequest.diagramLine instance requires (TString) txEndpointID

**Comment by KeyBridge** [comment]
resolved in final release
